[[redirects]]
  from = "/keep-teaching"
  to = "https://keepteaching.ucsc.edu"
  status = 301
  headers = {X-From = "Netlify"}
  force = true
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.ucsc.edu *.google-analytics.com ajax.googleapis.com *.googletagmanager.com use.fontawesome.com *.google.com *.netlify.com *.unpkg.com fonts.googleapis.com fonts.gstatic.com unpkg.com *.fontawesome.com;frame-src 'self' *.youtube.com *.google.com;object-src 'none';frame-ancestors 'self' *.google.com *.youtube.com;"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

